// Generated by CoffeeScript 1.6.3
(function() {
  var SlideshowCtrl, slideshowApp;

  slideshowApp = angular.module('slideshowApp', []);

  SlideshowCtrl = (function() {
    SlideshowCtrl.$inject = ['$scope', '$http', '$sce', '$location'];

    function SlideshowCtrl(scope, http, sce, location) {
      var _this = this;
      this.scope = scope;
      this.http = http;
      this.sce = sce;
      this.location = location;
      this.popup_active = '';
      this.selected_year = {};
      this.http.get('data/slideshow.json').success(function(data) {
        var year;
        _this.data = data;
        year = _this.location.search().year;
        if (year !== void 0 && _this.data[year] !== void 0 && _this.data[year].enabled === "") {
          return _this.selected_year = data[year];
        } else {
          return _this.selected_year = data['1992'];
        }
      });
    }

    SlideshowCtrl.prototype.selectYear = function(year) {
      this.data[this.selected_year.year].is_active = "";
      this.selected_year = this.data[year];
      return this.data[year].is_active = "active";
    };

    SlideshowCtrl.prototype.next = function() {
      if (this.selected_year.next > 0) {
        return this.selectYear(this.selected_year.next);
      }
    };

    SlideshowCtrl.prototype.prev = function() {
      if (this.selected_year.prev > 0) {
        return this.selectYear(this.selected_year.prev);
      }
    };

    SlideshowCtrl.prototype.togglePopup = function() {
      if (this.popup_active === 'hide') {
        return this.popup_active = "";
      } else {
        return this.popup_active = "hide";
      }
    };

    SlideshowCtrl.prototype.selectedGraphText = function() {
      return this.sce.trustAsHtml(this.selected_year.graph_text);
    };

    SlideshowCtrl.prototype.getHtml = function(text) {
      return this.sce.trustAsHtml(text);
    };

    SlideshowCtrl.prototype.getThumbnail = function() {
      if (this.popup_active !== "hide" && this.selected_year.year > 0) {
        return this.selected_year.graph_thumbnail;
      } else {
        return this.selected_year.thumbnail;
      }
    };

    return SlideshowCtrl;

  })();

  slideshowApp.controller('SlideshowCtrl', SlideshowCtrl);

}).call(this);
