// Generated by CoffeeScript 1.6.3
(function() {
  var SlideshowJSON, ViewModel,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  SlideshowJSON = [
    {
      year: 1990,
      empty: true,
      active: false
    }, {
      year: 1991,
      empty: true,
      active: false
    }, {
      year: 1992,
      active: true,
      empty: false,
      thumb_title: '<span>COP15</span> COPENHAGEN',
      graph: {
        large: 'images/graph-2009-large.jpg',
        thumb: 'images/graph-2009-thumb.jpg',
        html: '<blockquote>\
              <p>"There is no time to waste. America has\
              made our choice. We have charted our\
              course, we have made our commitments,\
              and we will do what we say."</p>\
              - <cite>Barack Obama, Copenhagen, Dec18 2009</cite>\
            </blockquote>'
      },
      modal: {
        large: 'images/graphic-2009-large.jpg',
        thumb: 'images/graphic-2009-thumb.jpg',
        meta: '<span>1992 COP15</span> COPENHAGEN ACCORD',
        title: 'Yes We Can\'t',
        text: '\
            <p>THERE IS new hope and a new president in the\
                        White House. A Nobel Peace Prize awaits him in\
                        Oslo. There is change in the air: Yes we can.</p>\
            <p>Heads of State, 115 of them, arrive-Wen Jiabao,\
                        Angela Merkel, Manmohan Singh, Gordon\
                        Brown, Lula Da Silva.What will they do?</p>\
            <p>Australia and US propose a new strategy.\
                        No global reduction targets, but each country\
                        decides how much and by when. US puts\
                        numbers as its way ahead: cut 0-3% over 1990\
                        levels by 2020. India and China also make\
                        their bid-all agree to do as little as possible.</p>\
            <p>Big polluters are happy at the high table.\
                        Their bait to the rest: US $30 billion in the\
                        short-term and US $100 billion by 2020.\
                        Carrot for the rabbits. Sticks for the Planet.\
                        But the plan goes horribly wrong. It is now\
                        24 hours after the conference should have\
                        ended. Small countries revolt. The accord is\
                        rejected. It is only noted.</p>\
            <p>Stripped all the way.</p>\
            '
      }
    }, {
      year: 1993,
      empty: true,
      active: false
    }, {
      year: 1994,
      empty: true,
      active: false
    }, {
      year: 1995,
      active: false,
      empty: false,
      thumb_title: '<span>COP14</span> COPENHAGEN',
      graph: {
        large: 'images/graph-2009-large.jpg',
        thumb: 'images/graph-2009-thumb.jpg',
        html: '<blockquote>\
              <p>"There is no time to waste. America has\
              made our choice. We have charted our\
              course, we have made our commitments,\
              and we will do what we say."</p>\
              - <cite>Barack Obama, Copenhagen, Dec18 2009</cite>\
            </blockquote>'
      },
      modal: {
        large: 'images/graphic-2009-large.jpg',
        thumb: 'images/graphic-2009-thumb.jpg',
        meta: '<span>1995 COP15</span> COPENHAGEN ACCORD',
        title: 'Yes We Can\'t',
        text: '\
            <p>THERE IS new hope and a new president in the\
                        White House. A Nobel Peace Prize awaits him in\
                        Oslo. There is change in the air: Yes we can.</p>\
            <p>Heads of State, 115 of them, arrive-Wen Jiabao,\
                        Angela Merkel, Manmohan Singh, Gordon\
                        Brown, Lula Da Silva.What will they do?</p>\
            <p>Australia and US propose a new strategy.\
                        No global reduction targets, but each country\
                        decides how much and by when. US puts\
                        numbers as its way ahead: cut 0-3% over 1990\
                        levels by 2020. India and China also make\
                        their bid-all agree to do as little as possible.</p>\
            <p>Big polluters are happy at the high table.\
                        Their bait to the rest: US $30 billion in the\
                        short-term and US $100 billion by 2020.\
                        Carrot for the rabbits. Sticks for the Planet.\
                        But the plan goes horribly wrong. It is now\
                        24 hours after the conference should have\
                        ended. Small countries revolt. The accord is\
                        rejected. It is only noted.</p>\
            <p>Stripped all the way.</p>\
            '
      }
    }, {
      year: 1996,
      empty: true,
      active: false
    }, {
      year: 1997,
      active: false,
      empty: false,
      thumb_title: '<span>COP13</span> COPENHAGEN',
      graph: {
        large: 'images/graph-2009-large.jpg',
        thumb: 'images/graph-2009-thumb.jpg',
        html: '<blockquote>\
              <p>"There is no time to waste. America has\
              made our choice. We have charted our\
              course, we have made our commitments,\
              and we will do what we say."</p>\
              - <cite>Barack Obama, Copenhagen, Dec18 2009</cite>\
            </blockquote>'
      },
      modal: {
        large: 'images/graphic-2009-large.jpg',
        thumb: 'images/graphic-2009-thumb.jpg',
        meta: '<span>1997 COP15</span> COPENHAGEN ACCORD',
        title: 'Yes We Can\'t',
        text: '\
            <p>THERE IS new hope and a new president in the\
                        White House. A Nobel Peace Prize awaits him in\
                        Oslo. There is change in the air: Yes we can.</p>\
            <p>Heads of State, 115 of them, arrive-Wen Jiabao,\
                        Angela Merkel, Manmohan Singh, Gordon\
                        Brown, Lula Da Silva.What will they do?</p>\
            <p>Australia and US propose a new strategy.\
                        No global reduction targets, but each country\
                        decides how much and by when. US puts\
                        numbers as its way ahead: cut 0-3% over 1990\
                        levels by 2020. India and China also make\
                        their bid-all agree to do as little as possible.</p>\
            <p>Big polluters are happy at the high table.\
                        Their bait to the rest: US $30 billion in the\
                        short-term and US $100 billion by 2020.\
                        Carrot for the rabbits. Sticks for the Planet.\
                        But the plan goes horribly wrong. It is now\
                        24 hours after the conference should have\
                        ended. Small countries revolt. The accord is\
                        rejected. It is only noted.</p>\
            <p>Stripped all the way.</p>\
            '
      }
    }, {
      year: 1998,
      empty: true,
      active: false
    }, {
      year: 1999,
      empty: true,
      active: false
    }, {
      year: 2000,
      empty: true,
      active: false
    }, {
      year: 2001,
      empty: true,
      active: false
    }, {
      year: 2002,
      empty: true,
      active: false
    }, {
      year: 2003,
      empty: true,
      active: false
    }, {
      year: 2004,
      active: false,
      empty: false,
      thumb_title: '<span>COP12</span> COPENHAGEN',
      graph: {
        large: 'images/graph-2009-large.jpg',
        thumb: 'images/graph-2009-thumb.jpg',
        html: '<blockquote>\
              <p>"There is no time to waste. America has\
              made our choice. We have charted our\
              course, we have made our commitments,\
              and we will do what we say."</p>\
              - <cite>Barack Obama, Copenhagen, Dec18 2009</cite>\
            </blockquote>'
      },
      modal: {
        large: 'images/graphic-2009-large.jpg',
        thumb: 'images/graphic-2009-thumb.jpg',
        meta: '<span>2004 COP15</span> COPENHAGEN ACCORD',
        title: 'Yes We Can\'t',
        text: '\
            <p>THERE IS new hope and a new president in the\
                        White House. A Nobel Peace Prize awaits him in\
                        Oslo. There is change in the air: Yes we can.</p>\
            <p>Heads of State, 115 of them, arrive-Wen Jiabao,\
                        Angela Merkel, Manmohan Singh, Gordon\
                        Brown, Lula Da Silva.What will they do?</p>\
            <p>Australia and US propose a new strategy.\
                        No global reduction targets, but each country\
                        decides how much and by when. US puts\
                        numbers as its way ahead: cut 0-3% over 1990\
                        levels by 2020. India and China also make\
                        their bid-all agree to do as little as possible.</p>\
            <p>Big polluters are happy at the high table.\
                        Their bait to the rest: US $30 billion in the\
                        short-term and US $100 billion by 2020.\
                        Carrot for the rabbits. Sticks for the Planet.\
                        But the plan goes horribly wrong. It is now\
                        24 hours after the conference should have\
                        ended. Small countries revolt. The accord is\
                        rejected. It is only noted.</p>\
            <p>Stripped all the way.</p>\
            '
      }
    }, {
      year: 2005,
      empty: true,
      active: false
    }, {
      year: 2006,
      empty: true,
      active: false
    }, {
      year: 2007,
      active: false,
      empty: false,
      thumb_title: '<span>COP11</span> COPENHAGEN',
      graph: {
        large: 'images/graph-2009-large.jpg',
        thumb: 'images/graph-2009-thumb.jpg',
        html: '<blockquote>\
              <p>"There is no time to waste. America has\
              made our choice. We have charted our\
              course, we have made our commitments,\
              and we will do what we say."</p>\
              - <cite>Barack Obama, Copenhagen, Dec18 2009</cite>\
            </blockquote>'
      },
      modal: {
        large: 'images/graphic-2009-large.jpg',
        thumb: 'images/graphic-2009-thumb.jpg',
        meta: '<span>2007 COP15</span> COPENHAGEN ACCORD',
        title: 'Yes We Can\'t',
        text: '\
            <p>THERE IS new hope and a new president in the\
                        White House. A Nobel Peace Prize awaits him in\
                        Oslo. There is change in the air: Yes we can.</p>\
            <p>Heads of State, 115 of them, arrive-Wen Jiabao,\
                        Angela Merkel, Manmohan Singh, Gordon\
                        Brown, Lula Da Silva.What will they do?</p>\
            <p>Australia and US propose a new strategy.\
                        No global reduction targets, but each country\
                        decides how much and by when. US puts\
                        numbers as its way ahead: cut 0-3% over 1990\
                        levels by 2020. India and China also make\
                        their bid-all agree to do as little as possible.</p>\
            <p>Big polluters are happy at the high table.\
                        Their bait to the rest: US $30 billion in the\
                        short-term and US $100 billion by 2020.\
                        Carrot for the rabbits. Sticks for the Planet.\
                        But the plan goes horribly wrong. It is now\
                        24 hours after the conference should have\
                        ended. Small countries revolt. The accord is\
                        rejected. It is only noted.</p>\
            <p>Stripped all the way.</p>\
            '
      }
    }, {
      year: 2008,
      empty: true,
      active: false
    }, {
      year: 2009,
      active: false,
      empty: false,
      thumb_title: '<span>COP10</span> COPENHAGEN',
      graph: {
        large: 'images/graph-2009-large.jpg',
        thumb: 'images/graph-2009-thumb.jpg',
        html: '<blockquote>\
              <p>"There is no time to waste. America has\
              made our choice. We have charted our\
              course, we have made our commitments,\
              and we will do what we say."</p>\
              - <cite>Barack Obama, Copenhagen, Dec18 2009</cite>\
            </blockquote>'
      },
      modal: {
        large: 'images/graphic-2009-large.jpg',
        thumb: 'images/graphic-2009-thumb.jpg',
        meta: '<span>2009 COP15</span> COPENHAGEN ACCORD',
        title: 'Yes We Can\'t',
        text: '\
            <p>THERE IS new hope and a new president in the\
                        White House. A Nobel Peace Prize awaits him in\
                        Oslo. There is change in the air: Yes we can.</p>\
            <p>Heads of State, 115 of them, arrive-Wen Jiabao,\
                        Angela Merkel, Manmohan Singh, Gordon\
                        Brown, Lula Da Silva.What will they do?</p>\
            <p>Australia and US propose a new strategy.\
                        No global reduction targets, but each country\
                        decides how much and by when. US puts\
                        numbers as its way ahead: cut 0-3% over 1990\
                        levels by 2020. India and China also make\
                        their bid-all agree to do as little as possible.</p>\
            <p>Big polluters are happy at the high table.\
                        Their bait to the rest: US $30 billion in the\
                        short-term and US $100 billion by 2020.\
                        Carrot for the rabbits. Sticks for the Planet.\
                        But the plan goes horribly wrong. It is now\
                        24 hours after the conference should have\
                        ended. Small countries revolt. The accord is\
                        rejected. It is only noted.</p>\
            <p>Stripped all the way.</p>\
            '
      }
    }, {
      year: 2010,
      active: false,
      empty: false,
      thumb_title: '<span>COP09</span> COPENHAGEN',
      graph: {
        large: 'images/graph-2009-large.jpg',
        thumb: 'images/graph-2009-thumb.jpg',
        html: '<blockquote>\
              <p>"There is no time to waste. America has\
              made our choice. We have charted our\
              course, we have made our commitments,\
              and we will do what we say."</p>\
              - <cite>Barack Obama, Copenhagen, Dec18 2009</cite>\
            </blockquote>'
      },
      modal: {
        large: 'images/graphic-2009-large.jpg',
        thumb: 'images/graphic-2009-thumb.jpg',
        meta: '<span>2010 COP15</span> COPENHAGEN ACCORD',
        title: 'Yes We Can\'t',
        text: '\
            <p>THERE IS new hope and a new president in the\
                        White House. A Nobel Peace Prize awaits him in\
                        Oslo. There is change in the air: Yes we can.</p>\
            <p>Heads of State, 115 of them, arrive-Wen Jiabao,\
                        Angela Merkel, Manmohan Singh, Gordon\
                        Brown, Lula Da Silva.What will they do?</p>\
            <p>Australia and US propose a new strategy.\
                        No global reduction targets, but each country\
                        decides how much and by when. US puts\
                        numbers as its way ahead: cut 0-3% over 1990\
                        levels by 2020. India and China also make\
                        their bid-all agree to do as little as possible.</p>\
            <p>Big polluters are happy at the high table.\
                        Their bait to the rest: US $30 billion in the\
                        short-term and US $100 billion by 2020.\
                        Carrot for the rabbits. Sticks for the Planet.\
                        But the plan goes horribly wrong. It is now\
                        24 hours after the conference should have\
                        ended. Small countries revolt. The accord is\
                        rejected. It is only noted.</p>\
            <p>Stripped all the way.</p>\
            '
      }
    }, {
      year: 2011,
      active: false,
      empty: false,
      thumb_title: '<span>COP08</span> COPENHAGEN',
      graph: {
        large: 'images/graph-2009-large.jpg',
        thumb: 'images/graph-2009-thumb.jpg',
        html: '<blockquote>\
              <p>"There is no time to waste. America has\
              made our choice. We have charted our\
              course, we have made our commitments,\
              and we will do what we say."</p>\
              - <cite>Barack Obama, Copenhagen, Dec18 2009</cite>\
            </blockquote>'
      },
      modal: {
        large: 'images/graphic-2009-large.jpg',
        thumb: 'images/graphic-2009-thumb.jpg',
        meta: '<span>2011 COP15</span> COPENHAGEN ACCORD',
        title: 'Yes We Can\'t',
        text: '\
            <p>THERE IS new hope and a new president in the\
                        White House. A Nobel Peace Prize awaits him in\
                        Oslo. There is change in the air: Yes we can.</p>\
            <p>Heads of State, 115 of them, arrive-Wen Jiabao,\
                        Angela Merkel, Manmohan Singh, Gordon\
                        Brown, Lula Da Silva.What will they do?</p>\
            <p>Australia and US propose a new strategy.\
                        No global reduction targets, but each country\
                        decides how much and by when. US puts\
                        numbers as its way ahead: cut 0-3% over 1990\
                        levels by 2020. India and China also make\
                        their bid-all agree to do as little as possible.</p>\
            <p>Big polluters are happy at the high table.\
                        Their bait to the rest: US $30 billion in the\
                        short-term and US $100 billion by 2020.\
                        Carrot for the rabbits. Sticks for the Planet.\
                        But the plan goes horribly wrong. It is now\
                        24 hours after the conference should have\
                        ended. Small countries revolt. The accord is\
                        rejected. It is only noted.</p>\
            <p>Stripped all the way.</p>\
            '
      }
    }, {
      year: 2012,
      active: false,
      empty: false,
      thumb_title: '<span>COP07</span> COPENHAGEN',
      graph: {
        large: 'images/graph-2009-large.jpg',
        thumb: 'images/graph-2009-thumb.jpg',
        html: '<blockquote>\
              <p>"There is no time to waste. America has\
              made our choice. We have charted our\
              course, we have made our commitments,\
              and we will do what we say."</p>\
              - <cite>Barack Obama, Copenhagen, Dec18 2009</cite>\
            </blockquote>'
      },
      modal: {
        large: 'images/graphic-2009-large.jpg',
        thumb: 'images/graphic-2009-thumb.jpg',
        meta: '<span>2012 COP15</span> COPENHAGEN ACCORD',
        title: 'Yes We Can\'t',
        text: '\
            <p>THERE IS new hope and a new president in the\
                        White House. A Nobel Peace Prize awaits him in\
                        Oslo. There is change in the air: Yes we can.</p>\
            <p>Heads of State, 115 of them, arrive-Wen Jiabao,\
                        Angela Merkel, Manmohan Singh, Gordon\
                        Brown, Lula Da Silva.What will they do?</p>\
            <p>Australia and US propose a new strategy.\
                        No global reduction targets, but each country\
                        decides how much and by when. US puts\
                        numbers as its way ahead: cut 0-3% over 1990\
                        levels by 2020. India and China also make\
                        their bid-all agree to do as little as possible.</p>\
            <p>Big polluters are happy at the high table.\
                        Their bait to the rest: US $30 billion in the\
                        short-term and US $100 billion by 2020.\
                        Carrot for the rabbits. Sticks for the Planet.\
                        But the plan goes horribly wrong. It is now\
                        24 hours after the conference should have\
                        ended. Small countries revolt. The accord is\
                        rejected. It is only noted.</p>\
            <p>Stripped all the way.</p>\
            '
      }
    }, {
      year: 2013,
      active: false,
      empty: false,
      thumb_title: '<span>COP06</span> COPENHAGEN',
      graph: {
        large: 'images/graph-2009-large.jpg',
        thumb: 'images/graph-2009-thumb.jpg',
        html: '<blockquote>\
              <p>"There is no time to waste. America has\
              made our choice. We have charted our\
              course, we have made our commitments,\
              and we will do what we say."</p>\
              - <cite>Barack Obama, Copenhagen, Dec18 2009</cite>\
            </blockquote>'
      },
      modal: {
        large: 'images/graphic-2009-large.jpg',
        thumb: 'images/graphic-2009-thumb.jpg',
        meta: '<span>2013 COP15</span> COPENHAGEN ACCORD',
        title: 'Yes We Can\'t',
        text: '\
            <p>THERE IS new hope and a new president in the\
                        White House. A Nobel Peace Prize awaits him in\
                        Oslo. There is change in the air: Yes we can.</p>\
            <p>Heads of State, 115 of them, arrive-Wen Jiabao,\
                        Angela Merkel, Manmohan Singh, Gordon\
                        Brown, Lula Da Silva.What will they do?</p>\
            <p>Australia and US propose a new strategy.\
                        No global reduction targets, but each country\
                        decides how much and by when. US puts\
                        numbers as its way ahead: cut 0-3% over 1990\
                        levels by 2020. India and China also make\
                        their bid-all agree to do as little as possible.</p>\
            <p>Big polluters are happy at the high table.\
                        Their bait to the rest: US $30 billion in the\
                        short-term and US $100 billion by 2020.\
                        Carrot for the rabbits. Sticks for the Planet.\
                        But the plan goes horribly wrong. It is now\
                        24 hours after the conference should have\
                        ended. Small countries revolt. The accord is\
                        rejected. It is only noted.</p>\
            <p>Stripped all the way.</p>\
            '
      }
    }
  ];

  ViewModel = (function() {
    function ViewModel(json) {
      this.prev = __bind(this.prev, this);
      this.next = __bind(this.next, this);
      this.getThumb = __bind(this.getThumb, this);
      this.selectYear = __bind(this.selectYear, this);
      this.data = ko.mapping.fromJS(json);
      this.selected = ko.observable(this.data()[2]);
      this.modal = ko.observable(false);
      window.dta = this.data;
    }

    ViewModel.prototype.selectYear = function(yData, e) {
      var current;
      current = this.selected();
      current.active(false);
      yData.active(true);
      return this.selected(yData);
    };

    ViewModel.prototype.getThumb = function() {
      if (this.modal()) {
        return this.selected().graph.thumb();
      } else {
        return this.selected().modal.thumb();
      }
    };

    ViewModel.prototype.toggleView = function() {
      return this.modal(!this.modal());
    };

    ViewModel.prototype.yearsWithData = function() {
      var y, y_w_d, _i, _len, _ref;
      y_w_d = [];
      _ref = this.data();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        y = _ref[_i];
        if (!y.empty()) {
          y_w_d.push(y.year());
        }
      }
      return y_w_d;
    };

    ViewModel.prototype.next = function() {
      var i, y, year, ywd, _i, _len, _ref, _results;
      year = this.selected().year();
      ywd = this.yearsWithData();
      i = ywd.indexOf(year);
      if (i + 1 === ywd.length) {
        year = ywd[0];
      } else {
        year = ywd[i + 1];
      }
      _ref = this.data();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        y = _ref[_i];
        if (y.year() === year) {
          _results.push(this.selectYear(y));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    ViewModel.prototype.prev = function() {
      var i, y, year, ywd, _i, _len, _ref, _results;
      year = this.selected().year();
      ywd = this.yearsWithData();
      i = ywd.indexOf(year);
      if (i) {
        year = ywd[i - 1];
      } else {
        year = ywd[ywd.length - 1];
      }
      _ref = this.data();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        y = _ref[_i];
        if (y.year() === year) {
          _results.push(this.selectYear(y));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return ViewModel;

  })();

  $(function() {
    var vm;
    vm = new ViewModel(SlideshowJSON);
    return ko.applyBindings(vm);
  });

}).call(this);
